apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "oomkill-exporter.fullname" . }}
  labels:
    {{- include "oomkill-exporter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "oomkill-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "oomkill-exporter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "oomkill-exporter.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ include "oomkill-exporter.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - --listen-address={{ .Values.config.listenAddress }}
        - --containerd-socket={{ .Values.config.containerdSocket }}
        - --containerd-namespace={{ .Values.config.containerdNamespace }}
        - --log-level={{ .Values.config.logLevel }}
        {{- if .Values.config.regexpPattern }}
        - --regexp-pattern={{ .Values.config.regexpPattern }}
        {{- end }}
        {{- with .Values.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        ports:
        - name: metrics
          containerPort: 9102
          protocol: TCP
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
        - name: kmsg
          mountPath: /dev/kmsg
          readOnly: true
        - name: containerd
          mountPath: {{ .Values.config.containerdSocket }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: kmsg
        hostPath:
          path: {{ .Values.hostPaths.kmsg }}
      - name: containerd
        hostPath:
          path: {{ .Values.hostPaths.containerdSocket }}
